2024-03-14 18:25:09,819 INFO    MainThread:1422 [wandb_setup.py:_flush():76] Configure stats pid to 1422
2024-03-14 18:25:09,819 INFO    MainThread:1422 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-03-14 18:25:09,819 INFO    MainThread:1422 [wandb_setup.py:_flush():76] Loading settings from /root/wj/stess/wandb/settings
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_require_service': 'True'}
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/root/wj/stess/train.py'}
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:_log_setup():461] Logging user logs to /root/wj/stess/wandb/run-20240314_182509-308zpuf1/logs/debug.log
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:_log_setup():462] Logging internal logs to /root/wj/stess/wandb/run-20240314_182509-308zpuf1/logs/debug-internal.log
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:init():495] calling init triggers
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:init():548] starting backend
2024-03-14 18:25:09,820 INFO    MainThread:1422 [wandb_init.py:init():552] setting up manager
2024-03-14 18:25:09,825 INFO    MainThread:1422 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-14 18:25:09,829 INFO    MainThread:1422 [wandb_init.py:init():558] backend started and connected
2024-03-14 18:25:09,833 INFO    MainThread:1422 [wandb_init.py:init():636] updated telemetry
2024-03-14 18:25:09,841 INFO    MainThread:1422 [wandb_init.py:init():667] communicating run to backend with 30 second timeout
2024-03-14 18:25:13,914 WARNING MsgRouterThr:1422 [router.py:message_loop():76] message_loop has been closed
2024-03-14 18:25:39,842 INFO    MainThread:1422 [interface_shared.py:_communicate_run():331] couldn't get run from backend
2024-03-14 18:25:39,842 ERROR   MainThread:1422 [wandb_init.py:init():676] backend process timed out
2024-03-14 18:25:39,843 ERROR   MainThread:1422 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
